[server]
maxUploadSize = 10
headless = true
enableXsrfProtection = true
enableCORS = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#203469"
backgroundColor = "#F8FAFD"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
