[server]
maxUploadSize = 10
headless = true
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#5B5FEF"
backgroundColor = "#F7FBFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#19324A"
